org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true

# Mod properties
mod_version = 0.1.0
mod_description = Gives wolves autonomous task completion capabilities, allowing them to perform useful work around your world.
mod_id = workingwolves
mod_name = Working Wolves
mod_authors = grill24
mod_license = All Rights Reserved
mod_icon = icon.png
mod_neoforge_version_range = [${neoforge_version},)
mod_minecraft_version_range = [${minecraft_version},)
mod_fabric_minecraft_version = ~${minecraft_version}
maven_group = grill24.workingwolves
archives_name = workingwolves
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 26.1.2

# Dependencies
fabric_loader_version = 0.19.1
fabric_api_version = 0.145.4+26.1.2
neoforge_version = 26.1.2.4-beta
